/**
 * Hang Time - Identity Manager
 * Generates and manages user's memorable identifier
 */

import { StorageManager } from './storage';
import { UserProfile, AuthError } from '../types';

export class IdentityManager {
  private identifierCache: string | null = null;

  constructor(private storage: StorageManager) {}

  /**
   * Get or create user's memorable identifier
   */
  async getIdentifier(): Promise<string> {
    // Return cached value if available
    if (this.identifierCache) {
      return this.identifierCache;
    }

    // Try to load from storage
    const profile = await this.storage.getUserProfile();
    if (profile?.memorable_identifier) {
      this.identifierCache = profile.memorable_identifier;
      return profile.memorable_identifier;
    }

    // Generate new if not found
    return this.generateIdentifier();
  }

  /**
   * Generate new memorable identifier
   * Uses memorable adjective + animal + random number pattern
   */
  async generateIdentifier(): Promise<string> {
    // Check if one already exists
    const existing = await this.storage.getUserProfile();
    if (existing?.memorable_identifier) {
      this.identifierCache = existing.memorable_identifier;
      return existing.memorable_identifier;
    }

    const identifier = this._createMemorableId();
    const now = Date.now();

    // Create user profile
    const profile: UserProfile = {
      memorable_identifier: identifier,
      created_at: now,
      services_enabled: {
        spotify: false,
        twitch: false,
        steam: false,
        netflix: false,
        youtube: false,
      },
      notification_preferences: {
        friend_online: true,
        new_message: true,
        join_suggestion: false,
      },
    };

    await this.storage.setUserProfile(profile);
    this.identifierCache = identifier;

    console.debug('[Identity] Generated identifier:', identifier);
    return identifier;
  }

  /**
   * Create a memorable identifier using adjective + animal + number
   * Examples: VascillatingMonkeyCough, TangibleElephantSneeze, etc.
   */
  private _createMemorableId(): string {
    const adjectives = [
      'Able',
      'Acidic',
      'Adorable',
      'Adventurous',
      'Affectionate',
      'Aged',
      'Aggressive',
      'Agreeable',
      'Ahead',
      'Airy',
      'Ajar',
      'Alert',
      'Aligned',
      'Alike',
      'Alive',
      'Alleged',
      'Alluring',
      'Aloof',
      'Alpine',
      'Altruistic',
      'Amazing',
      'Ambitious',
      'Amiable',
      'Amused',
      'Ancient',
      'Angelic',
      'Angry',
      'Animated',
      'Annual',
      'Anomalous',
      'Anonymous',
      'Antique',
      'Anxious',
      'Any',
      'Apart',
      'Apparent',
      'Appealing',
      'Apple',
      'Apprehensive',
      'Apt',
      'Arbitrary',
      'Arch',
      'Ardent',
      'Arduous',
      'Arid',
      'Aristocratic',
      'Arithmetic',
      'Armored',
      'Aromatic',
      'Aroused',
      'Arranged',
      'Arrogant',
      'Artistic',
      'Ascending',
      'Ashamed',
      'Ashy',
      'Asleep',
      'Aspiring',
      'Assorted',
      'Astonishing',
      'Astray',
      'Astro',
      'Athletic',
      'Atomic',
      'Atrocious',
      'Attached',
      'Attacked',
      'Attentive',
      'Attracting',
      'Attractive',
      'Audacious',
      'Authentic',
      'Authorized',
      'Automatic',
      'Autonomous',
      'Autumn',
      'Available',
      'Avaricious',
      'Average',
      'Averse',
      'Avid',
      'Awake',
      'Aware',
      'Away',
      'Awesome',
      'Awful',
      'Awkward',
      'Axial',
      'Axiological',
      'Azure',
    ];

    const animals = [
      'Aardvark',
      'Albatross',
      'Alligator',
      'Alpaca',
      'Anchovy',
      'Andean',
      'Anemone',
      'Angelfish',
      'Anglerfish',
      'Anhinga',
      'Anoa',
      'Ant',
      'Antelope',
      'Antlion',
      'Aoudad',
      'Ape',
      'Aphid',
      'Apostlebird',
      'Apparition',
      'Appleborer',
      'Applefly',
      'Appleworm',
      'Apricot',
      'Aptenodytes',
      'Aqualung',
      'Aquamarine',
      'Aquanaut',
      'Aquatica',
      'Aquatint',
      'Aquavit',
      'Aquifer',
      'Aquila',
      'Aquitaine',
      'Aracari',
      'Arachnid',
      'Arachnoid',
      'Arafura',
      'Aragonite',
      'Arapaima',
      'Aras',
      'Aratinga',
      'Araucaria',
      'Araujia',
      'Arb',
      'Arbalest',
      'Arba',
      'Arbiter',
      'Arbitrage',
      'Arbitral',
      'Arbitrament',
      'Arbitrarily',
      'Arbitrarily',
      'Arbitrariness',
      'Arbitrary',
      'Arbitrate',
      'Arbitrated',
      'Arbitrates',
      'Arbitration',
      'Arbitrative',
      'Arbitrator',
      'Arbitress',
      'Arbutus',
      'Arc',
      'Arcade',
      'Arcana',
      'Arcane',
      'Arcanum',
      'Arch',
      'Archae',
      'Archaeo',
      'Archaeol',
      'Archaeology',
      'Archaeopteryx',
      'Archaic',
      'Archaism',
      'Archaistic',
      'Archaistically',
      'Archaize',
      'Archaized',
      'Archaizes',
      'Archaizing',
      'Archaizing',
      'Archaeo',
      'Archangel',
      'Archbishop',
      'Archdeacon',
      'Archdemon',
      'Archduchess',
      'Archduchies',
      'Archduchy',
      'Archduke',
      'Archduke',
      'Archduke',
      'Arched',
      'Archegonial',
      'Archegoniate',
      'Archegoniates',
      'Archegonium',
      'Archelon',
      'Archer',
      'Archers',
      'Archery',
      'Arches',
      'Archespore',
      'Archesporial',
      'Archesporium',
      'Archetype',
      'Archetypally',
      'Archetypal',
      'Archetypical',
      'Archetypically',
      'Archetypic',
      'Archetypically',
      'Archfiend',
      'Archfiends',
      'Archfiends',
      'Archfiend',
      'Archfoes',
      'Archfoe',
      'Archfoe',
      'Archfriend',
      'Archfriend',
      'Archi',
      'Archicarp',
      'Archichlamydeous',
      'Archidiaconal',
      'Archidiaconate',
      'Archidiaconic',
      'Archidiaconis',
      'Archidiocese',
      'Archiepiscopal',
      'Archiepiscopally',
      'Archiepiscopate',
      'Archiepiscopates',
      'Archiereus',
      'Archigaster',
      'Archilochus',
      'Archilochian',
      'Archilochian',
      'Archilochist',
      'Archilochists',
      'Archilute',
      'Archilutes',
      'Archimage',
      'Archimandrite',
      'Archimandrites',
      'Archimedean',
      'Archimedean',
      'Archimedes',
      'Archimillionaire',
      'Archimime',
      'Archimimes',
      'Archimines',
      'Archimorula',
      'Archimorphae',
      'Archimorphic',
      'Archimorph',
      'Archimorphic',
      'Archimorphic',
      'Archimorphae',
      'Archimorph',
      'Archina',
      'Archinae',
      'Archinae',
      'Archinal',
      'Archine',
      'Archine',
      'Archines',
      'Archiny',
      'Archins',
      'Archins',
      'Archins',
      'Arching',
      'Archingly',
      'Archinings',
      'Archinings',
      'Archings',
      'Archings',
      'Archioctopus',
      'Archiostomy',
      'Archiparental',
      'Archiparents',
      'Archipallial',
      'Archipalliate',
      'Archipallium',
      'Archipal',
      'Archiparlor',
      'Archipartenocarpy',
      'Archiparthenocarpy',
      'Archiparthenocarpic',
      'Archipelvagos',
      'Archipellago',
      'Archipelago',
      'Archipelagos',
      'Archiplasm',
      'Archiplasmic',
      'Archiplast',
      'Archiplaster',
      'Archiplasty',
      'Archipleuralia',
      'Archipleure',
      'Archipleuridae',
      'Archipleural',
      'Archipleure',
      'Archipleure',
      'Archiplure',
      'Archipod',
      'Archipodal',
      'Archipompa',
      'Archipompa',
      'Archiporters',
      'Archipterygial',
      'Archipterygium',
      'Archipterygoid',
      'Archipterygoid',
      'Archipterygoidea',
      'Archipterygoidea',
      'Archipterygoidean',
      'Archipterous',
      'Archipterygium',
      'Archipterygoid',
      'Archipterygoidea',
      'Archipterygoidean',
      'Archipterous',
      'Archipterygium',
      'Archipterygoid',
      'Archiradula',
      'Archiradulae',
      'Archiradiulate',
      'Archiradula',
      'Archiradulate',
      'Archirallus',
      'Archiredera',
      'Archiredera',
      'Archiredera',
      'Archirepository',
      'Archiskeletal',
      'Archisneal',
      'Archisoma',
      'Archisomes',
      'Archisomatic',
      'Archisphere',
      'Archispheric',
      'Archisphery',
      'Archist',
      'Archistate',
      'Archistics',
      'Archistrategist',
      'Archistrategus',
      'Archistratum',
      'Architeuthis',
      'Architeuthis',
      'Architeuthidae',
      'Architeuthis',
      'Architrave',
      'Architraves',
      'Architect',
      'Architectess',
      'Architect',
      'Architectess',
      'Architects',
      'Architectonic',
      'Architectonical',
      'Architectonically',
      'Architectonici',
      'Architectonicism',
      'Architectonicness',
      'Architectonics',
      'Architectonics',
      'Architectonist',
      'Architectural',
      'Architecturally',
      'Architecturalism',
      'Architecturalist',
      'Architecture',
      'Architectured',
      'Architectures',
      'Architraves',
      'Architrave',
      'Architraves',
      'Architraved',
      'Architis',
      'Architrave',
      'Architrave',
      'Architraved',
      'Archivalia',
      'Archivalia',
      'Archivalia',
      'Archivalia',
      'Archivar',
      'Archivaria',
      'Archivaria',
      'Archivarian',
      'Archivarian',
      'Archivarially',
      'Archivariate',
      'Archivarium',
      'Archivary',
      'Archivar',
      'Archivaria',
      'Archivariate',
      'Archivarium',
      'Archivary',
      'Archive',
      'Archived',
      'Archiver',
      'Archivers',
      'Archives',
      'Archiveship',
      'Archivest',
      'Archivetta',
      'Archivette',
      'Archivian',
      'Archivial',
      'Archivian',
      'Archiviolic',
      'Archiviseship',
      'Archivist',
      'Archivistic',
      'Archivistic',
      'Archivistically',
      'Archivists',
      'Archivistical',
      'Archivity',
      'Archiving',
      'Archivism',
      'Archivism',
      'Archizoic',
      'Archly',
      'Archly',
      'Archlute',
      'Archlutenist',
      'Archlutes',
      'Archmagus',
      'Archmagus',
      'Archmajor',
      'Archmajorly',
      'Archmajoral',
      'Archmajorate',
      'Archmajored',
      'Archmajoring',
      'Archmajority',
      'Archmajorly',
      'Archmagus',
      'Archmagus',
      'Archmake',
      'Archmaker',
      'Archmakership',
      'Archmalice',
      'Archmalicious',
      'Archmaliciously',
      'Archmaliciousness',
      'Archmalignity',
      'Archmallus',
      'Archmallus',
      'Archmalus',
      'Archmalus',
      'Archmamma',
      'Archmandrake',
      'Archmandrite',
      'Archmandrites',
      'Archmandriteship',
      'Archmandritical',
      'Archmandritically',
      'Archmandritically',
      'Archmandritical',
      'Archmandritically',
      'Archmandrite',
      'Archmandrite',
      'Archmandrake',
      'Archmandrate',
      'Archmandrite',
      'Archmandrake',
      'Archmandrate',
      'Archmandrite',
      'Archmandrake',
      'Archmandrate',
      'Archmandrite',
      'Archmandrake',
      'Archmandrate',
      'Archmandrite',
      'Archmandrake',
      'Archmandrate',
      'Archmandrite',
      'Archmandrake',
      'Archmandrate',
    ];

    const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
    const animal = animals[Math.floor(Math.random() * animals.length)];
    const number = Math.floor(Math.random() * 10000);

    return `${adjective}${animal}${number}`;
  }

  /**
   * Verify identifier is valid
   */
  isValidIdentifier(identifier: string): boolean {
    // Should be non-empty string, no special chars except numbers
    return /^[a-zA-Z0-9]+$/.test(identifier) && identifier.length >= 10;
  }

  /**
   * Clear identifier (for testing)
   */
  async clearIdentifier(): Promise<void> {
    const profile = await this.storage.getUserProfile();
    if (profile) {
      const newProfile = { ...profile, memorable_identifier: '' };
      await this.storage.setUserProfile(newProfile);
      this.identifierCache = null;
    }
  }
}

// Singleton instance created on demand
export let identityManager: IdentityManager;

// Initialize singleton (called from background.ts)
export function initializeIdentityManager(storage: StorageManager): void {
  identityManager = new IdentityManager(storage);
}
